name: "Test GHALogger"
on:
  workflow_dispatch:

jobs:
  log_stuff:
    runs-on: ["ubuntu-22.04"]
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Run Tests
        run: "swift test"
