name: "Test GHALogger"
on:
  workflow_dispatch:

jobs:
  log_stuff:
    runs-on: ["ubuntu-22.04"]
    steps:
      - name: Install Swift
        run: |
          export SWIFTLY_READ_FROM_STDIN=1
          curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash
          swiftly install latest
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Run Tests
        run: "swift test"
